# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dakota Sanchez
tagline:          'site'
description:      'PNW-based Software Engineer'
url:              http://dakotasanchez.com
baseurl:          /

author:
  name:           'Dakota Sanchez'
  url:            

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/dakotasanchez
