# Dependencies
markdown:         kramdown
kramdown:
    input: GFM
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dakota Sanchez
tagline:          'site'
description:      'Software Engineer'
url:              http://dakotasanchez.com
baseurl:          /
about_me_url:     '/#About me'
resume_url:		  '/#Resume'

author:
  name:           'Dakota Sanchez'
  url:            

paginate:         5

# Custom vars
version:          1.1

github:
  repo:           https://github.com/dakotasanchez
