# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dakota Sanchez
tagline:          'site'
description:      'PNW-Based Software Engineer'
url:              http://dakotasanchez.com
baseurl:          /
about_me_url:     '/#About me'
resume_url:		  '/#Résumé'

author:
  name:           'Dakota Sanchez'
  url:            

paginate:         5

# Custom vars
version:          1.1

github:
  repo:           https://github.com/dakotasanchez
